// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

export interface IpcApi {
  counter: {
    get(): Promise<number>
    inc(by?: number): Promise<number>
    ping(): Promise<string>
    reset(): void
  }
  echo: {
    complex(input: ComplexPayload): Promise<ComplexPayload>
    simple(input: SimplePayload): Promise<SimplePayload>
    onceInvoke(msg: string): Promise<string>
    fireAndForget(msg: string): void
    onceListen(): void
  }
  util: {
    withOrigin(): Promise<{ hasFrame: boolean }>
    withRawEvent(): Promise<{ senderId: number }>
  }
}

declare global {
  interface Window {
    ipc: IpcApi
  }
}

export {}
