version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm-workspace-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-workspace-major:
        patterns:
          - "*"
        update-types:
          - "major"
