import type { ControllerMetadata } from "../parser/types.js";

import { buildNamespaces } from "./build-namespaces.js";
import { buildTypeDefinitions } from "./build-type-definitions.js";

export const generateRuntimeTypes = (controllers: ControllerMetadata[]): string => {
  const referenceTypes = Array.from(new Set(controllers.flatMap((c) => c.requiredReferenceTypes ?? []))).sort();
  const referenceDirectives = referenceTypes.map((refType) => `/// <reference types="${refType}" />`).join("\n");
  const typeDefinitions = buildTypeDefinitions(controllers);
  const namespaces = buildNamespaces(controllers);

  const sections = ["// Auto-generated by @electron-ipc-bridge/vite-plugin", "// Do not edit manually", ""];
  if (referenceDirectives) {
    sections.push(referenceDirectives, "");
  }
  if (typeDefinitions) {
    sections.push(typeDefinitions, "");
  }

  return `${sections.join("\n")}
export interface IpcApi {
${namespaces.join("\n")}
}
`;
};
